### ISSUE TITLE
ErrorException in FileViewFinder.php line 137:

### ISSUE THREAD

**Issue by johnslay** [qjroundy/MigraineTracker#23]
```
 View [trigger.view] not found. (View: /home/vagrant/Code/MigraineTracker/resources/views/user/edit.blade.php)
```

Happens when I try to edit my profile.

**Comment by qjr3** [comment]
I changed several file names to their proper REST names. and since we were including views inside of views without controller intervention, I also separated out those as p_show or p_index to include in another view, and just show and index for the ones that are their own full pages. I thought I had all the links updated but must've missed some.

**Comment by qjr3** [comment]
Also, I switched to an AJAX approach to adding triggers and medication on the profile page. it's not complete yet but that will throw some errors if you try to add them atm
