### ISSUE TITLE
Home page ugly as ....

### ISSUE THREAD

**Issue by johnslay** [qjroundy/MigraineTracker#36]
The login and register form on the home page........ needs to be eliminated imho

**Comment by qjr3** [comment]
They belong there so when people go to the front page they can login immediately. This is how most sites do it because most people don't want to see a shout page (unless it also has a login). Generally, the only sites that do not have the login on the front page are those which you can use without logging into first to use (like amazon, ebay, youtube etc). Sites you have to sign into to use (or to use most features) have the login on front. This is actually for a number of reason. When you bookmark a site, you bookmark the front page (generally) and people who use autologin want to be able to go to the front page and be immediately logged in. For example, I use facebook. I have www.facebook.com bookmarked. I shouldn't have to click my bookmark and then have to take further action to use the the services Facebook offer. You will note that (if not signed in) Facebook's front page has a registration page and login both. Some sites use a trick, which if we had time I would prefer and I think you would too, of hiding the login behind an invisible form, which then allows a front page without login form, but still allows for autologin to work. A good example of this is GoDaddy.com and Twitter even. Another exception are sites that people don't typically go to the main site to use them but rather use a proxy page. In these cases it would be normal to have a shout page instead, PayPal falls into this category. Most people who use paypal login when they are actually buying something (which does have a a login on the page. By putting it off the front page you severely inconvenience your clients. 

As for the register, that's different. If you want that can be reduced to a simple link and moved to a separate page. These decisions by big companies are not on accident either, they are based on market research. Most people share these preferences. If you want to move them back off, fine, but if this was a real project you would be inconveniencing most of your users. I was considering putting the login back on the navbar. I think it would fit if we removed the resource links when not logged in. So if they go to the front page and are not logged in the nav bar would be only the brand, and a login form and if logged in they would see the resource links and their user name as it is now. This would actually be best (and is also a common approach to the problem. If you want I can make that change tonight, but either way the login form needs to be on front page if you want users to be happier.

**Comment by qjr3** [comment]
Also, nobody who wants to use a service wants to type, like many people who do type urls manually as well, www.example.com/login or was it www.example.com/user/login or maybe it was www.example.com/wp-login (yep, that's Wordpress) or my favorite, is the login page even in the same domain or subdomain?  Let me ask you, without even looking, what is the manual login page uri for YT (that would be: https://accounts.google.com/ServiceLogin..........)? , or a better example, without looking, what is the manual login uri for my.uwf.edu? Do you know? (hint: it's https://id.uwf.edu/cas/login) And yes, I know that UWF doesn't have the login form on the front page....but that's because you can navigate the my.uwf.edu without being logged in (such as before you are registered student)

**Comment by johnslay** [comment]
yeah they should be in there own side panel or, like you said, in the navbar. Taking up the entire screen is just obnoxious. Looks ok for mobile, but not web.

**Comment by qjr3** [comment]
If I can do a mobile detect then I will put it in the nav bar on no login and non-mobile, otherwise it will show in the main panel. Does that make sense? IF tablet/laptop/desktop if not logged in then the main page will be the shout page and the login form (only) will be in the navbar and a link to register (not a button). If mobile the nav bar will only have the brand and linkto register and the main panel will display login form (not registration form). That sound like a good plan?
